services:
  web:
    image: connectx-web
    build:
      context: ./src
      dockerfile: WebServices/ConnectX.Web/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__cache: cache:6379
    ports:
      - "5078:8080"
    depends_on:
      api:
        condition: service_started
      cache:
        condition: service_healthy

  api:
    image: connectx-api
    build:
      context: ./src
      dockerfile: ApiServices/ConnectX.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
    ports:
      - "5110:8080"

  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
